[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next/standalone"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  YOUTUBE_API_KEY = "AIzaSyCmsFreWdDFd0nAb3cG8lPCSCWrQBgrB_s"
  NEWS_API_KEY = "0a3970c61b3346f28a0cfa28d0be700a"
  # Other API keys should be set in the Netlify dashboard for security

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {type = "404"}
